fix the app and remove the warning
eclipse/microprofile-starter pull request #414
Opened 2021-04-07 17:25 UTC by Emily-Jiang

Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

2021-04-08 08:28 UTC, rdebusscher requested changes

2021-04-08 08:28 UTC, rdebusscher commented on src/main/resources/files/BookingController.java.tpl
> -                                    ref = "Booking",
Without the ref value, the OpenAPI document inlines the definition of Booking and no longer reference it.  This change is not wanted!

2021-04-08 08:37 UTC, rdebusscher commented
<img width="870" alt="openAPI compare" src="https://user-images.githubusercontent.com/1228265/113995165-4a887b80-9856-11eb-8659-a47f8c643ea5.png">

2021-04-08 14:52 UTC, Emily-Jiang commented
@rdebusscher I did test against Open Liberty. Prior to the change, I did not see the referenced schema.
```
paths:
  /data/booking/{bookingId}:
    get:
      operationId: getBooking
      parameters:
      - name: bookingId
        in: path
        required: true
        style: simple
        schema:
          type: string
      responses:
        "200":
          description: Booking for id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        "404":
          description: No booking found for the id.

```
I then tested payara micro before my change (out of box) on MP 3.3 as MP 4.0  is not working (start.microprofile.io). I got the following:
```
paths:
  /data/booking/{bookingId}:
    get:
      operationId: getBooking
      parameters:
      - name: bookingId
        in: path
        required: true
        style: simple
        schema:
          type: string
      responses:
        "200":
          description: Booking for id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        "404":
          description: No booking found for the id.
```

2021-04-11 15:59 UTC, rdebusscher commented
See #416

2021-04-21 10:57 UTC, Emily-Jiang commented
I've tested against the runtimes Payara, Wildfly and they are ok. The change demonstrates the usage based on the mp openapi spec.

2021-04-22 18:17 UTC, rdebusscher approved these changes
LGTM

2021-04-22 21:24 UTC, merged